/* FellaPC Firmaware
 * Keyboard
 * Copyright: Aleksander Kaminski, 2024
 * See LICENSE.md
 */

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#include "keys.h"
#include "keyboard.h"

struct keys keyboard_keys = { 0 };

const uint8_t keymap_main[5][16] = {
{
	KEY_ESC, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
	KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_HOME
},
{
	KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P,
	KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_BACKSLASH, KEY_DELETE
},
{
	KEY_CAPSLOCK, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L,
	KEY_SEMICOLON, KEY_APOSTROPHE, KEY_NONE, KEY_ENTER, KEY_PAGEUP
},
{
	KEY_LEFTSHIFT, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_DOT,
	KEY_SLASH, KEY_NONE, KEY_RIGHTSHIFT, KEY_UP, KEY_PAGEDOWN
},
{
	KEY_LEFTCTRL, KEY_LEFTMETA, KEY_LEFTALT, KEY_NONE, KEY_NONE, KEY_SPACE, KEY_NONE,
	KEY_NONE, KEY_RIGHTALT, KEY_NONE, KEY_RIGHTCTRL, KEY_FN, KEY_LEFT, KEY_DOWN, KEY_RIGHT
} };

/* Row 0 only */
const uint8_t keymap_alt[16] = { KEY_GRAVE, KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5,
	KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_F11, KEY_F12, KEY_BACKSPACE, KEY_END };
